const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getToday: () => ipcRenderer.invoke('tasks:getToday'),
  getUpcoming: () => ipcRenderer.invoke('tasks:getUpcoming'),
  addTask: (payload) => ipcRenderer.invoke('tasks:add', payload),
  toggleDone: (id) => ipcRenderer.invoke('tasks:toggleDone', id),
  deleteTask: (id) => ipcRenderer.invoke('tasks:delete', id),
  updatePos: (id, x, y) => ipcRenderer.invoke('tasks:updatePos', { id, x, y }),
  abrirInstagram: () => ipcRenderer.invoke('autor:instagram'),
  getAgua: () => ipcRenderer.invoke('agua:get'),
  setAgua: (patch) => ipcRenderer.invoke('agua:set', patch),
  testarAgua: () => ipcRenderer.invoke('agua:testar'),
  fecharLembrete: () => ipcRenderer.invoke('lembrete:fechar'),
  onAguaChanged: (cb) => ipcRenderer.on('agua-changed', (_e, cfg) => cb(cfg)),
  onLembrete: (cb) => ipcRenderer.on('lembrete', (_e, dados) => cb(dados)),
  onLembreteSaindo: (cb) => ipcRenderer.on('lembrete-saindo', () => cb()),
  listSkins: () => ipcRenderer.invoke('skins:list'),
  getSkin: () => ipcRenderer.invoke('skins:current'),
  setSkin: (id) => ipcRenderer.invoke('skins:set', id),
  onSkinChanged: (cb) => ipcRenderer.on('skin-changed', (_e, skin) => cb(skin)),
  getPinned: () => ipcRenderer.invoke('pin:get'),
  togglePinned: () => ipcRenderer.invoke('pin:toggle'),
  onPinChanged: (cb) => ipcRenderer.on('pin-changed', (_e, pinned) => cb(pinned)),
  openBoard: () => ipcRenderer.invoke('board:open'),
  hidePanel: () => ipcRenderer.invoke('panel:hide'),
  closeBoard: () => ipcRenderer.invoke('board:close'),
  getTodayStr: () => ipcRenderer.invoke('today:get'),
  onTasksChanged: (cb) => ipcRenderer.on('tasks-changed', cb),
});
